CREATE TABLE "matriculas" (
	"id" serial PRIMARY KEY NOT NULL,
	"status" varchar(20) DEFAULT 'pendente' NOT NULL,
	"serie" varchar(50) NOT NULL,
	"turno" varchar(20) NOT NULL,
	"nome_aluno" text NOT NULL,
	"data_nascimento" date NOT NULL,
	"sexo" varchar(1) NOT NULL,
	"cor_raca" varchar(30) NOT NULL,
	"naturalidade" text NOT NULL,
	"sus" varchar(20),
	"cpf_aluno" varchar(14),
	"nome_pai" text,
	"nome_mae" text NOT NULL,
	"endereco" text NOT NULL,
	"telefones" text NOT NULL,
	"telefone2" text,
	"telefone3" text,
	"email_contato" text,
	"zona_residencia" varchar(7) NOT NULL,
	"utiliza_transporte_escolar" boolean DEFAULT false NOT NULL,
	"possui_problema_saude" boolean DEFAULT false NOT NULL,
	"qual_problema_saude" text,
	"faz_uso_medicacao" boolean DEFAULT false NOT NULL,
	"possui_relatorio_medico" boolean DEFAULT false NOT NULL,
	"apresenta_alergia" boolean DEFAULT false NOT NULL,
	"qual_alergia" text,
	"possui_deficiencia_ou_tgd" boolean DEFAULT false NOT NULL,
	"def_cegueira" boolean DEFAULT false NOT NULL,
	"def_baixa_visao" boolean DEFAULT false NOT NULL,
	"def_surdez" boolean DEFAULT false NOT NULL,
	"def_autismo_infantil" boolean DEFAULT false NOT NULL,
	"def_sindrome_asperger" boolean DEFAULT false NOT NULL,
	"def_altas_habilidades_superdotacao" boolean DEFAULT false NOT NULL,
	"def_surdocegueira" boolean DEFAULT false NOT NULL,
	"def_fisica" boolean DEFAULT false NOT NULL,
	"def_sindrome_rett" boolean DEFAULT false NOT NULL,
	"def_transtorno_desintegrativo" boolean DEFAULT false NOT NULL,
	"def_auditiva_infancia" boolean DEFAULT false NOT NULL,
	"def_intelectual" boolean DEFAULT false NOT NULL,
	"def_multipla" boolean DEFAULT false NOT NULL,
	"recebe_bolsa_familia" boolean DEFAULT false NOT NULL,
	"numero_nis" varchar(15),
	"autorizo_uso_imagem" boolean DEFAULT false NOT NULL,
	"nome_responsavel" text NOT NULL,
	"rg_responsavel" varchar(14) NOT NULL,
	"cpf_responsavel" varchar(14) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" text NOT NULL,
	"email" text NOT NULL,
	"senha" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
